language: python
sudo: false
python:
- 3.6
script:
  - pip install .
  - pytest --cov=./
  - python -c "import wyriwyd; print(wyriwyd)"
  - wyriwyd-test README.md

after_success:
  - pip install codecov
  - codecov
