#!/bin/bash

read -p "Output file name (.md): " outfile
rm -f "$outfile"

echo -e "Start typing your commands. When done, press enter.
File $outfile containing the session will be genarated."

mysys="$(uname -s)"
tmpfile="/tmp/wyriwyd.log"
rm -f "$tmpfile"

while read -p "$ " command && test -n "$command" ; do
    if [ "$mysys" = "Linux" ]; then
        output="$(script -c "$command" -q -- "$tmpfile" | sed 's/\r$//')"
    elif [ "$mysys" = "Darwin" ]; then
        output="$(script -q "$tmpfile" "$command" | sed 's/\r$//')"
    else
        echo "Unknown system"
        return 1
    fi
    echo -e "$output\n"
    if [ -n "$output" ]; then
        echo -e "\`\`\`bash\n${command}\n\`\`\`\n\n\`\`\`output\n$output\n\`\`\`\n" >> "$outfile"
    else
        echo -e "\`\`\`bash\n${command}\n\`\`\`\n" >> "$outfile"
    fi
done

rm -f "$tmpfile"
